version: "2"

services:
  # https://github.com/nadoo/glider
  glider:
    build: glider
    network_mode: host

  # https://hub.docker.com/r/tailscale/tailscale
  tailscale:
    image: tailscale/tailscale:v1.52.0
    restart: "on-failure"
    environment:
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_SOCKET: "/var/run/tailscale/tailscaled.sock"
      TS_EXTRA_ARGS: "--reset --accept-routes --advertise-exit-node"
      # TS_USERSPACE: "false"
      TS_AUTH_ONCE: "false"
      # TS_HOSTNAME: exit-node
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    volumes:
      - tailscale-state:/var/lib/tailscale
    tmpfs:
      - /tmp
      - /var/run/
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        case "${DISABLE}" in
          [Tt][Rr][Uu][Ee]|[Yy][Ee][Ss]|[Oo][Nn]|[1])
            exit 0
            ;;
        esac
        if modprobe wireguard 2>/dev/null
        then
          modinfo wireguard || true
        fi
        mkdir -p /dev/net
        [ ! -c /dev/net/tun ] && mknod /dev/net/tun c 10 200
        /usr/local/bin/containerboot

volumes:
  tailscale-state: {}
