version: "2"

services:
  # https://github.com/nadoo/glider
  glider:
    build: glider
    network_mode: host

  # https://github.com/klutchell/balena-tailscale
  tailscale:
    build: tailscale
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    tmpfs:
      - /tmp
      - /var/run
