
ARG BALENA_ARCH=%%BALENA_ARCH%%

# https://github.com/klutchell/balena-tailscale
FROM bh.cr/gh_klutchell/tailscale-amd64/6ce0aae761660822cda0872e5634698b:1.88.3-rev1 AS balena-tailscale-amd64
FROM bh.cr/gh_klutchell/tailscale-aarch64/b1c53c65a4b16b7535aa15d3cc3b0e76:1.88.3-rev1 AS balena-tailscale-aarch64
FROM bh.cr/gh_klutchell/tailscale-armv7hf/1178eb49ab291e4edb353eb4fd48c954:1.88.3-rev1 AS balena-tailscale-armv7hf

# hadolint ignore=DL3006
FROM balena-tailscale-${BALENA_ARCH}

# ENV TS_HOSTNAME="exit-node"
ENV TS_EXTRA_ARGS="--reset --accept-routes --advertise-exit-node"
