
ARG BALENA_ARCH=%%BALENA_ARCH%%

# https://github.com/klutchell/balena-tailscale
FROM bh.cr/gh_klutchell/tailscale-amd64/66a7bcdbbc93727843cf53d638bd50b9:1.90.9-rev2 AS balena-tailscale-amd64
FROM bh.cr/gh_klutchell/tailscale-aarch64/5fa5e9b5ebf60585645c00d9b18acc5e:1.90.9-rev2 AS balena-tailscale-aarch64
FROM bh.cr/gh_klutchell/tailscale-armv7hf/8b6daba89ae7d91f2806156077a3e729:1.90.9-rev2 AS balena-tailscale-armv7hf

# hadolint ignore=DL3006
FROM balena-tailscale-${BALENA_ARCH}

# ENV TS_HOSTNAME="exit-node"
ENV TS_EXTRA_ARGS="--reset --accept-routes --advertise-exit-node"
