
ARG BALENA_ARCH=%%BALENA_ARCH%%

# https://github.com/klutchell/balena-tailscale
FROM bh.cr/gh_klutchell/tailscale-amd64/3ba313efabe27c0ef3925f8926791d96:1.84.1 AS balena-tailscale-amd64
FROM bh.cr/gh_klutchell/tailscale-aarch64/839f5b38a1c33dc7096840b62aedfff7:1.84.1 AS balena-tailscale-aarch64
FROM bh.cr/gh_klutchell/tailscale-armv7hf/932f58a166b2511b9f4982d3dff8fe79:1.84.1 AS balena-tailscale-armv7hf

# hadolint ignore=DL3006
FROM balena-tailscale-${BALENA_ARCH}

# ENV TS_HOSTNAME="exit-node"
ENV TS_EXTRA_ARGS="--reset --accept-routes --advertise-exit-node"
